version: "3.3"
services:
  mongodb:
    image: mongo:4
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ~/usservice_mongo:/data/db
    ports:
      - "27018:27018"
    networks:
      - mongo_net
    command: --port 27018

  us-service:
    build: .
    ports:
      - "8080:8080"
    container_name: us-service
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
